local ObjectDB = ObjectDB; for objectID,objectData in pairs({
	[473943] = {
		readable = "Salvageable Scrap",
		model = 1103093,
		text = {
			en = "Salvageable Scrap",
			es = "Salvageable Scrap",
			de = "Salvageable Scrap",
			fr = "Salvageable Scrap",
			it = "Salvageable Scrap",
			pt = "Salvageable Scrap",
			ru = "Salvageable Scrap",
			ko = "Salvageable Scrap",
			cn = "Salvageable Scrap",
		},
	},
	[474030] = {
		readable = "Salvageable Scrap",
		model = 1611709,
		text = {
			en = "Salvageable Scrap",
			es = "Salvageable Scrap",
			de = "Salvageable Scrap",
			fr = "Salvageable Scrap",
			it = "Salvageable Scrap",
			pt = "Salvageable Scrap",
			ru = "Salvageable Scrap",
			ko = "Salvageable Scrap",
			cn = "Salvageable Scrap",
		},
	},
	[474033] = {
		readable = "Salvageable Scrap",
		model = 1121294,
		text = {
			en = "Salvageable Scrap",
			es = "Salvageable Scrap",
			de = "Salvageable Scrap",
			fr = "Salvageable Scrap",
			it = "Salvageable Scrap",
			pt = "Salvageable Scrap",
			ru = "Salvageable Scrap",
			ko = "Salvageable Scrap",
			cn = "Salvageable Scrap",
		},
	},
	[474084] = {
		readable = "Salvageable Scrap",
		model = 1140791,
		text = {
			en = "Salvageable Scrap",
			es = "Salvageable Scrap",
			de = "Salvageable Scrap",
			fr = "Salvageable Scrap",
			it = "Salvageable Scrap",
			pt = "Salvageable Scrap",
			ru = "Salvageable Scrap",
			ko = "Salvageable Scrap",
			cn = "Salvageable Scrap",
		},
	},
	[474086] = {
		readable = "Salvageable Scrap",
		model = 2261829,
		text = {
			en = "Salvageable Scrap",
			es = "Salvageable Scrap",
			de = "Salvageable Scrap",
			fr = "Salvageable Scrap",
			it = "Salvageable Scrap",
			pt = "Salvageable Scrap",
			ru = "Salvageable Scrap",
			ko = "Salvageable Scrap",
			cn = "Salvageable Scrap",
		},
	},
})
do ObjectDB[objectID] = objectData; end