local ObjectDB = ObjectDB; for objectID,objectData in pairs({
	[499127] = {
		readable = "Runemarked Coffer",
		model = 1402264,
		text = {
			en = "Runemarked Coffer",
			es = "Runemarked Coffer",
			de = "Runemarked Coffer",
			fr = "Runemarked Coffer",
			it = "Runemarked Coffer",
			pt = "Runemarked Coffer",
			ru = "Runemarked Coffer",
			ko = "Runemarked Coffer",
			cn = "Runemarked Coffer",
		},
	},
	[499443] = {
		readable = "Faded Journal Page",
		model = 3978479,
		text = {
			en = "Faded Journal Page",
			es = "Faded Journal Page",
			de = "Faded Journal Page",
			fr = "Faded Journal Page",
			it = "Faded Journal Page",
			pt = "Faded Journal Page",
			ru = "Faded Journal Page",
			ko = "Faded Journal Page",
			cn = "Faded Journal Page",
		},
	},
	[500407] = {
		readable = "Runed Storm Cache",
		model = 1402270,
		text = {
			en = "Runed Storm Cache",
			es = "Runed Storm Cache",
			de = "Runed Storm Cache",
			fr = "Runed Storm Cache",
			it = "Runed Storm Cache",
			pt = "Runed Storm Cache",
			ru = "Runed Storm Cache",
			ko = "Runed Storm Cache",
			cn = "Runed Storm Cache",
		},
	},
	[500689] = {
		readable = "Seafarer's Cache",
		model = 219372,
		text = {
			en = "Seafarer's Cache",
			es = "Seafarer's Cache",
			de = "Seafarer's Cache",
			fr = "Seafarer's Cache",
			it = "Seafarer's Cache",
			pt = "Seafarer's Cache",
			ru = "Seafarer's Cache",
			ko = "Seafarer's Cache",
			cn = "Seafarer's Cache",
		},
	},
	[500690] = {
		readable = "Seafarer's Cache",
		model = 446671,
		text = {
			en = "Seafarer's Cache",
			es = "Seafarer's Cache",
			de = "Seafarer's Cache",
			fr = "Seafarer's Cache",
			it = "Seafarer's Cache",
			pt = "Seafarer's Cache",
			ru = "Seafarer's Cache",
			ko = "Seafarer's Cache",
			cn = "Seafarer's Cache",
		},
	},
})
do ObjectDB[objectID] = objectData; end