local ObjectDB = ObjectDB; for objectID,objectData in pairs({
	[495500] = {
		readable = "Shadowflame Cache",
		model = 199748,
		text = {
			en = "Shadowflame Cache",
			es = "[Shadowflame Cache]",
			de = "Schattenflammentruhe",
			fr = "Cache d’Ombreflamme",
			it = "[Shadowflame Cache]",
			pt = "[Shadowflame Cache]",
			ru = "[Shadowflame Cache]",
			ko = "암흑불길 보관함",
			cn = "[Shadowflame Cache]",
		},
	},
	[495503] = {
		readable = "Chromatic Hoard",
		model = 200953,
		text = {
			en = "Chromatic Hoard",
			es = "[Chromatic Hoard]",
			de = "Chromatischer Hort",
			fr = "Trésor chromatique",
			it = "[Chromatic Hoard]",
			pt = "[Chromatic Hoard]",
			ru = "[Chromatic Hoard]",
			ko = "오색 비축품",
			cn = "[Chromatic Hoard]",
		},
	},
	[495505] = {
		readable = "Favored Riches",
		model = 200953,
		text = {
			en = "Favored Riches",
			es = "[Favored Riches]",
			de = "Begünstigter Reichtum",
			fr = "Richesse chérie",
			it = "[Favored Riches]",
			pt = "[Favored Riches]",
			ru = "[Favored Riches]",
			ko = "총애받는 보물",
			cn = "[Favored Riches]",
		},
	},
	[495577] = {
		readable = "Chromatic Stash",
		model = 200953,
		text = {
			en = "Chromatic Stash",
			es = "[Chromatic Stash]",
			de = "[Chromatic Stash]",
			fr = "[Chromatic Stash]",
			it = "[Chromatic Stash]",
			pt = "[Chromatic Stash]",
			ru = "[Chromatic Stash]",
			ko = "[Chromatic Stash]",
			cn = "[Chromatic Stash]",
		},
	},
	[495578] = {
		readable = "Chromatic Supplies",
		model = 200953,
		text = {
			en = "Chromatic Supplies",
			es = "[Chromatic Supplies]",
			de = "[Chromatic Supplies]",
			fr = "[Chromatic Supplies]",
			it = "[Chromatic Supplies]",
			pt = "[Chromatic Supplies]",
			ru = "[Chromatic Supplies]",
			ko = "[Chromatic Supplies]",
			cn = "[Chromatic Supplies]",
		},
	},
})
do ObjectDB[objectID] = objectData; end