local ObjectDB = ObjectDB; for objectID,objectData in pairs({
	[465183] = {
		readable = "Mysterious Bones",
		model = 4690413,
		text = {
			en = "Mysterious Bones",
			es = "[Mysterious Bones]",
			de = "[Mysterious Bones]",
			fr = "[Mysterious Bones]",
			it = "[Mysterious Bones]",
			pt = "[Mysterious Bones]",
			ru = "[Mysterious Bones]",
			ko = "[Mysterious Bones]",
			cn = "[Mysterious Bones]",
		},
	},
	[466118] = {
		readable = "Unfinished Note",
		model = 936413,
		text = {
			en = "Unfinished Note",
			es = "[Unfinished Note]",
			de = "[Unfinished Note]",
			fr = "[Unfinished Note]",
			it = "[Unfinished Note]",
			pt = "[Unfinished Note]",
			ru = "[Unfinished Note]",
			ko = "[Unfinished Note]",
			cn = "[Unfinished Note]",
		},
	},
	[466119] = {
		readable = "Hastily Scrawled Note",
		model = 936413,
		text = {
			en = "Hastily Scrawled Note",
			es = "[Hastily Scrawled Note]",
			de = "[Hastily Scrawled Note]",
			fr = "[Hastily Scrawled Note]",
			it = "[Hastily Scrawled Note]",
			pt = "[Hastily Scrawled Note]",
			ru = "[Hastily Scrawled Note]",
			ko = "[Hastily Scrawled Note]",
			cn = "[Hastily Scrawled Note]",
		},
	},
	[466120] = {
		readable = "Water-Resistant Note",
		model = 936413,
		text = {
			en = "Water-Resistant Note",
			es = "[Water-Resistant Note]",
			de = "[Water-Resistant Note]",
			fr = "[Water-Resistant Note]",
			it = "[Water-Resistant Note]",
			pt = "[Water-Resistant Note]",
			ru = "[Water-Resistant Note]",
			ko = "[Water-Resistant Note]",
			cn = "[Water-Resistant Note]",
		},
	},
	[466128] = {
		readable = "Peculiar Gem",
		model = 1282671,
		text = {
			en = "Peculiar Gem",
			es = "[Peculiar Gem]",
			de = "[Peculiar Gem]",
			fr = "[Peculiar Gem]",
			it = "[Peculiar Gem]",
			pt = "[Peculiar Gem]",
			ru = "[Peculiar Gem]",
			ko = "[Peculiar Gem]",
			cn = "[Peculiar Gem]",
		},
	},
	[469327] = {
		readable = "Play Script",
		model = 936429,
		text = {
			en = "Play Script",
			es = "[Play Script]",
			de = "[Play Script]",
			fr = "[Play Script]",
			it = "[Play Script]",
			pt = "[Play Script]",
			ru = "[Play Script]",
			ko = "[Play Script]",
			cn = "[Play Script]",
		},
	},
	[469332] = {
		readable = "Prop Sword",
		model = 1361976,
		text = {
			en = "Prop Sword",
			es = "[Prop Sword]",
			de = "[Prop Sword]",
			fr = "[Prop Sword]",
			it = "[Prop Sword]",
			pt = "[Prop Sword]",
			ru = "[Prop Sword]",
			ko = "[Prop Sword]",
			cn = "[Prop Sword]",
		},
	},
	[469334] = {
		readable = "Mask of the Trickster",
		model = 1357703,
		text = {
			en = "Mask of the Trickster",
			es = "[Mask of the Trickster]",
			de = "[Mask of the Trickster]",
			fr = "[Mask of the Trickster]",
			it = "[Mask of the Trickster]",
			pt = "[Mask of the Trickster]",
			ru = "[Mask of the Trickster]",
			ko = "[Mask of the Trickster]",
			cn = "[Mask of the Trickster]",
		},
	},
	[469335] = {
		readable = "Conductor's Baton",
		model = 3036134,
		text = {
			en = "Conductor's Baton",
			es = "[Conductor's Baton]",
			de = "[Conductor's Baton]",
			fr = "[Conductor's Baton]",
			it = "[Conductor's Baton]",
			pt = "[Conductor's Baton]",
			ru = "[Conductor's Baton]",
			ko = "[Conductor's Baton]",
			cn = "[Conductor's Baton]",
		},
	},
})
do ObjectDB[objectID] = objectData; end