local ObjectDB = ObjectDB; for objectID,objectData in pairs({
	[430284] = {
		readable = "Radiant Remnant",
		model = 5869303,
		text = {
			en = "Radiant Remnant",
			es = "Remanente radiante",
			de = "Strahlendes Überbleibsel",
			fr = "Vestige radieux",
			it = "Residuo Radioso",
			pt = "Resquício Radiante",
			ru = "Сияющие останки",
			ko = "광휘의 잔재",
			cn = "光耀残渣",
		},
	},
	[430344] = {
		readable = "Radiant Remnant",
		model = 5869303,
		text = {
			en = "Radiant Remnant",
			es = "Remanente radiante",
			de = "Strahlendes Überbleibsel",
			fr = "Vestige radieux",
			it = "Residuo Radioso",
			pt = "Radiant Remnant",
			ru = "Сияющие останки",
			ko = "Radiant Remnant",
			cn = "Radiant Remnant",
		},
	},
	[430345] = {
		readable = "Radiant Remnant",
		model = 5869303,
		text = {
			en = "Radiant Remnant",
			es = "Remanente radiante",
			de = "Strahlendes Überbleibsel",
			fr = "Vestige radieux",
			it = "Residuo Radioso",
			pt = "Resquício Radiante",
			ru = "Сияющие останки",
			ko = "광휘의 잔재",
			cn = "光耀残渣",
		},
	},
	[430358] = {
		readable = "Radiant Remnant",
		model = 5869303,
		text = {
			en = "Radiant Remnant",
			es = "Remanente radiante",
			de = "Strahlendes Überbleibsel",
			fr = "Vestige radieux",
			it = "Residuo Radioso",
			pt = "Resquício Radiante",
			ru = "Сияющие останки",
			ko = "광휘의 잔재",
			cn = "光耀残渣",
		},
	},
	[434281] = {
		readable = "Radiant Remnant",
		model = 5869303,
		text = {
			en = "Radiant Remnant",
			es = "Radiant Remnant",
			de = "Strahlendes Überbleibsel",
			fr = "Vestige radieux",
			it = "Radiant Remnant",
			pt = "Radiant Remnant",
			ru = "Сияющие останки",
			ko = "광휘의 잔재",
			cn = "Radiant Remnant",
		},
	},
	[434283] = {
		readable = "Radiant Remnant",
		model = 5869303,
		text = {
			en = "Radiant Remnant",
			es = "Radiant Remnant",
			de = "Strahlendes Überbleibsel",
			fr = "Vestige radieux",
			it = "Radiant Remnant",
			pt = "Resquício Radiante",
			ru = "Сияющие останки",
			ko = "Radiant Remnant",
			cn = "Radiant Remnant",
		},
	},
	[434284] = {
		readable = "Radiant Remnant",
		model = 5869303,
		text = {
			en = "Radiant Remnant",
			es = "Remanente radiante",
			de = "Strahlendes Überbleibsel",
			fr = "Vestige radieux",
			it = "Radiant Remnant",
			pt = "Resquício Radiante",
			ru = "Сияющие останки",
			ko = "광휘의 잔재",
			cn = "光耀残渣",
		},
	},
	[434286] = {
		readable = "Radiant Remnant",
		model = 5869303,
		text = {
			en = "Radiant Remnant",
			es = "Remanente radiante",
			de = "Strahlendes Überbleibsel",
			fr = "Vestige radieux",
			it = "Residuo Radioso",
			pt = "Resquício Radiante",
			ru = "Сияющие останки",
			ko = "광휘의 잔재",
			cn = "光耀残渣",
		},
	},
	[434288] = {
		readable = "Radiant Remnant",
		model = 5869303,
		text = {
			en = "Radiant Remnant",
			es = "Remanente radiante",
			de = "Strahlendes Überbleibsel",
			fr = "Vestige radieux",
			it = "Radiant Remnant",
			pt = "Radiant Remnant",
			ru = "Сияющие останки",
			ko = "Radiant Remnant",
			cn = "光耀残渣",
		},
	},
	[434289] = {
		readable = "Radiant Remnant",
		model = 5869303,
		text = {
			en = "Radiant Remnant",
			es = "Radiant Remnant",
			de = "Strahlendes Überbleibsel",
			fr = "Vestige radieux",
			it = "Radiant Remnant",
			pt = "Radiant Remnant",
			ru = "Сияющие останки",
			ko = "Radiant Remnant",
			cn = "光耀残渣",
		},
	},
	[434560] = {
		readable = "Radiant Remnant",
		model = 5869303,
		text = {
			en = "Radiant Remnant",
			es = "Remanente radiante",
			de = "Strahlendes Überbleibsel",
			fr = "Vestige radieux",
			it = "Residuo Radioso",
			pt = "Resquício Radiante",
			ru = "Сияющие останки",
			ko = "광휘의 잔재",
			cn = "Radiant Remnant",
		},
	},
	[434563] = {
		readable = "Radiant Remnant",
		model = 5869303,
		text = {
			en = "Radiant Remnant",
			es = "Remanente radiante",
			de = "Strahlendes Überbleibsel",
			fr = "Vestige radieux",
			it = "Residuo Radioso",
			pt = "Resquício Radiante",
			ru = "Сияющие останки",
			ko = "광휘의 잔재",
			cn = "光耀残渣",
		},
	},
	[434565] = {
		readable = "Radiant Remnant",
		model = 5869303,
		text = {
			en = "Radiant Remnant",
			es = "Remanente radiante",
			de = "Strahlendes Überbleibsel",
			fr = "Vestige radieux",
			it = "Residuo Radioso",
			pt = "Resquício Radiante",
			ru = "Сияющие останки",
			ko = "광휘의 잔재",
			cn = "光耀残渣",
		},
	},
	[434566] = {
		readable = "Radiant Remnant",
		model = 5869303,
		text = {
			en = "Radiant Remnant",
			es = "Remanente radiante",
			de = "Strahlendes Überbleibsel",
			fr = "Vestige radieux",
			it = "Residuo Radioso",
			pt = "Resquício Radiante",
			ru = "Сияющие останки",
			ko = "광휘의 잔재",
			cn = "光耀残渣",
		},
	},
	[434567] = {
		readable = "Radiant Remnant",
		model = 5869303,
		text = {
			en = "Radiant Remnant",
			es = "Remanente radiante",
			de = "Strahlendes Überbleibsel",
			fr = "Vestige radieux",
			it = "Residuo Radioso",
			pt = "Resquício Radiante",
			ru = "Сияющие останки",
			ko = "광휘의 잔재",
			cn = "光耀残渣",
		},
	},
	[434568] = {
		readable = "Radiant Remnant",
		model = 5869303,
		text = {
			en = "Radiant Remnant",
			es = "Remanente radiante",
			de = "Strahlendes Überbleibsel",
			fr = "Vestige radieux",
			it = "Residuo Radioso",
			pt = "Resquício Radiante",
			ru = "Сияющие останки",
			ko = "광휘의 잔재",
			cn = "光耀残渣",
		},
	},
	[434925] = {
		readable = "Radiant Remnant",
		model = 5869303,
		text = {
			en = "Radiant Remnant",
			es = "Remanente radiante",
			de = "Strahlendes Überbleibsel",
			fr = "Vestige radieux",
			it = "Radiant Remnant",
			pt = "Resquício Radiante",
			ru = "Сияющие останки",
			ko = "광휘의 잔재",
			cn = "光耀残渣",
		},
	},
	[434927] = {
		readable = "Radiant Remnant",
		model = 5869303,
		text = {
			en = "Radiant Remnant",
			es = "Remanente radiante",
			de = "Strahlendes Überbleibsel",
			fr = "Vestige radieux",
			it = "Residuo Radioso",
			pt = "Resquício Radiante",
			ru = "Сияющие останки",
			ko = "광휘의 잔재",
			cn = "光耀残渣",
		},
	},
	[434928] = {
		readable = "Radiant Remnant",
		model = 5869303,
		text = {
			en = "Radiant Remnant",
			es = "Remanente radiante",
			de = "Strahlendes Überbleibsel",
			fr = "Vestige radieux",
			it = "Radiant Remnant",
			pt = "Resquício Radiante",
			ru = "Сияющие останки",
			ko = "Radiant Remnant",
			cn = "Radiant Remnant",
		},
	},
	[434930] = {
		readable = "Radiant Remnant",
		model = 5869303,
		text = {
			en = "Radiant Remnant",
			es = "Remanente radiante",
			de = "Strahlendes Überbleibsel",
			fr = "Vestige radieux",
			it = "Residuo Radioso",
			pt = "Resquício Radiante",
			ru = "Сияющие останки",
			ko = "광휘의 잔재",
			cn = "光耀残渣",
		},
	},
	[434932] = {
		readable = "Radiant Remnant",
		model = 5869303,
		text = {
			en = "Radiant Remnant",
			es = "Remanente radiante",
			de = "Strahlendes Überbleibsel",
			fr = "Radiant Remnant",
			it = "Radiant Remnant",
			pt = "Radiant Remnant",
			ru = "Radiant Remnant",
			ko = "Radiant Remnant",
			cn = "光耀残渣",
		},
	},
	[451990] = {
		readable = "Radiant Remnant",
		model = 5869303,
		text = {
			en = "Radiant Remnant",
			es = "Radiant Remnant",
			de = "Strahlendes Überbleibsel",
			fr = "Vestige radieux",
			it = "Radiant Remnant",
			pt = "Radiant Remnant",
			ru = "Сияющие останки",
			ko = "Radiant Remnant",
			cn = "Radiant Remnant",
		},
	},
	[454541] = {
		readable = "Radiant Remnant",
		model = 5869303,
		text = {
			en = "Radiant Remnant",
			es = "Remanente radiante",
			de = "Strahlendes Überbleibsel",
			fr = "Vestige radieux",
			it = "Residuo Radioso",
			pt = "Resquício Radiante",
			ru = "Сияющие останки",
			ko = "광휘의 잔재",
			cn = "光耀残渣",
		},
	},
	[454542] = {
		readable = "Radiant Remnant",
		model = 5869303,
		text = {
			en = "Radiant Remnant",
			es = "Remanente radiante",
			de = "Strahlendes Überbleibsel",
			fr = "Vestige radieux",
			it = "Residuo Radioso",
			pt = "Radiant Remnant",
			ru = "Сияющие останки",
			ko = "광휘의 잔재",
			cn = "光耀残渣",
		},
	},
	[457303] = {
		readable = "Radiant Remnant",
		model = 5869303,
		text = {
			en = "Radiant Remnant",
			es = "Remanente radiante",
			de = "Strahlendes Überbleibsel",
			fr = "Vestige radieux",
			it = "Residuo Radioso",
			pt = "Resquício Radiante",
			ru = "Сияющие останки",
			ko = "광휘의 잔재",
			cn = "光耀残渣",
		},
	},
})
do ObjectDB[objectID] = objectData; end