local ObjectDB = ObjectDB; for objectID,objectData in pairs({
	[467305] = {
		readable = "Toy Box",
		model = 4252799,
		text = {
			en = "Toy Box",
			es = "[Toy Box]",
			de = "[Toy Box]",
			fr = "[Toy Box]",
			it = "[Toy Box]",
			pt = "[Toy Box]",
			ru = "[Toy Box]",
			ko = "[Toy Box]",
			cn = "[Toy Box]",
		},
	},
	[472068] = {
		readable = "Bakar Sketch",
		model = 936413,
		text = {
			en = "Bakar Sketch",
			es = "[Bakar Sketch]",
			de = "[Bakar Sketch]",
			fr = "[Bakar Sketch]",
			it = "[Bakar Sketch]",
			pt = "[Bakar Sketch]",
			ru = "[Bakar Sketch]",
			ko = "[Bakar Sketch]",
			cn = "[Bakar Sketch]",
		},
	},
	[472077] = {
		readable = "Maru's Toy",
		model = 4615240,
		text = {
			en = "Maru's Toy",
			es = "[Maru's Toy]",
			de = "[Maru's Toy]",
			fr = "[Maru's Toy]",
			it = "[Maru's Toy]",
			pt = "[Maru's Toy]",
			ru = "[Maru's Toy]",
			ko = "[Maru's Toy]",
			cn = "[Maru's Toy]",
		},
	},
	[487825] = {
		readable = "Ruffled Pages",
		model = 936429,
		text = {
			en = "Ruffled Pages",
			es = "Ruffled Pages",
			de = "Ruffled Pages",
			fr = "Ruffled Pages",
			it = "Ruffled Pages",
			pt = "Ruffled Pages",
			ru = "Ruffled Pages",
			ko = "Ruffled Pages",
			cn = "Ruffled Pages",
		},
	},
	[494923] = {
		readable = "Tattered Journal",
		model = 4337371,
		text = {
			en = "Tattered Journal",
			es = "Tattered Journal",
			de = "Tattered Journal",
			fr = "Tattered Journal",
			it = "Tattered Journal",
			pt = "Tattered Journal",
			ru = "Tattered Journal",
			ko = "Tattered Journal",
			cn = "Tattered Journal",
		},
	},
})
do ObjectDB[objectID] = objectData; end