local ObjectDB = ObjectDB; for objectID,objectData in pairs({
	[455320] = {
		readable = "Vizier's Appreciation",
		model = 5007036,
		text = {
			en = "Vizier's Appreciation",
			es = "Agradecimiento del visir",
			de = "Anerkennung des Wesirs",
			fr = "Appréciation du vizir",
			it = "Vizier's Appreciation",
			pt = "Gratidão do Vizir",
			ru = "Знак признательности визиря",
			ko = "재상의 감사 표시",
			cn = "Vizier's Appreciation",
		},
	},
	[455324] = {
		readable = "Vizier's Appreciation",
		model = 5007036,
		text = {
			en = "Vizier's Appreciation",
			es = "Agradecimiento del visir",
			de = "Anerkennung des Wesirs",
			fr = "Appréciation du vizir",
			it = "Apprezzamento del Visir",
			pt = "Vizier's Appreciation",
			ru = "Знак признательности визиря",
			ko = "재상의 감사 표시",
			cn = "宰相的感激",
		},
	},
	[455328] = {
		readable = "Vizier's Appreciation",
		model = 5007036,
		text = {
			en = "Vizier's Appreciation",
			es = "Agradecimiento del visir",
			de = "Anerkennung des Wesirs",
			fr = "Appréciation du vizir",
			it = "Apprezzamento del Visir",
			pt = "Gratidão do Vizir",
			ru = "Знак признательности визиря",
			ko = "Vizier's Appreciation",
			cn = "宰相的感激",
		},
	},
	[455330] = {
		readable = "Vizier's Appreciation",
		model = 5007036,
		text = {
			en = "Vizier's Appreciation",
			es = "Agradecimiento del visir",
			de = "Anerkennung des Wesirs",
			fr = "Appréciation du vizir",
			it = "Apprezzamento del Visir",
			pt = "Gratidão do Vizir",
			ru = "Знак признательности визиря",
			ko = "Vizier's Appreciation",
			cn = "Vizier's Appreciation",
		},
	},
})
do ObjectDB[objectID] = objectData; end