local ObjectDB = ObjectDB; for objectID,objectData in pairs({
	[454707] = {
		readable = "Bag of Stolen Goods",
		model = 1254955,
		text = {
			en = "Bag of Stolen Goods",
			es = "Bag of Stolen Goods",
			de = "Bag of Stolen Goods",
			fr = "Bag of Stolen Goods",
			it = "Bag of Stolen Goods",
			pt = "Bag of Stolen Goods",
			ru = "Bag of Stolen Goods",
			ko = "Bag of Stolen Goods",
			cn = "Bag of Stolen Goods",
		},
	},
	[456665] = {
		readable = "Ore Sample",
		model = 5306874,
		text = {
			en = "Ore Sample",
			es = "Ore Sample",
			de = "Ore Sample",
			fr = "Ore Sample",
			it = "Ore Sample",
			pt = "Ore Sample",
			ru = "Ore Sample",
			ko = "Ore Sample",
			cn = "Ore Sample",
		},
	},
	[457143] = {
		readable = "Kaja'Cola Can",
		model = 331512,
		text = {
			en = "Kaja'Cola Can",
			es = "Kaja'Cola Can",
			de = "Kaja'Cola Can",
			fr = "Kaja'Cola Can",
			it = "Kaja'Cola Can",
			pt = "Kaja'Cola Can",
			ru = "Kaja'Cola Can",
			ko = "Kaja'Cola Can",
			cn = "Kaja'Cola Can",
		},
	},
	[463539] = {
		readable = "Pilfered Earthen Chest",
		model = 5128194,
		text = {
			en = "Pilfered Earthen Chest",
			es = "Pilfered Earthen Chest",
			de = "Pilfered Earthen Chest",
			fr = "Pilfered Earthen Chest",
			it = "Pilfered Earthen Chest",
			pt = "Pilfered Earthen Chest",
			ru = "Pilfered Earthen Chest",
			ko = "Pilfered Earthen Chest",
			cn = "Pilfered Earthen Chest",
		},
	},
	[464233] = {
		readable = "Bilge Rat Supply Chest",
		model = 1806321,
		text = {
			en = "Bilge Rat Supply Chest",
			es = "Bilge Rat Supply Chest",
			de = "Bilge Rat Supply Chest",
			fr = "Bilge Rat Supply Chest",
			it = "Bilge Rat Supply Chest",
			pt = "Bilge Rat Supply Chest",
			ru = "Bilge Rat Supply Chest",
			ko = "Bilge Rat Supply Chest",
			cn = "Bilge Rat Supply Chest",
		},
	},
	[465208] = {
		readable = "Crystal Chunk",
		model = 5869303,
		text = {
			en = "Crystal Chunk",
			es = "Crystal Chunk",
			de = "Crystal Chunk",
			fr = "Crystal Chunk",
			it = "Crystal Chunk",
			pt = "Crystal Chunk",
			ru = "Crystal Chunk",
			ko = "Crystal Chunk",
			cn = "Crystal Chunk",
		},
	},
	[465272] = {
		readable = "Empty Kaja'Cola Can",
		model = 331512,
		text = {
			en = "Empty Kaja'Cola Can",
			es = "Empty Kaja'Cola Can",
			de = "Empty Kaja'Cola Can",
			fr = "Empty Kaja'Cola Can",
			it = "Empty Kaja'Cola Can",
			pt = "Empty Kaja'Cola Can",
			ru = "Empty Kaja'Cola Can",
			ko = "Empty Kaja'Cola Can",
			cn = "Empty Kaja'Cola Can",
		},
	},
	[465294] = {
		readable = "Antonidas' Introduction to Arcane Magic",
		model = 985165,
		text = {
			en = "Antonidas' Introduction to Arcane Magic",
			es = "Antonidas' Introduction to Arcane Magic",
			de = "Antonidas' Introduction to Arcane Magic",
			fr = "Antonidas' Introduction to Arcane Magic",
			it = "Antonidas' Introduction to Arcane Magic",
			pt = "Antonidas' Introduction to Arcane Magic",
			ru = "Antonidas' Introduction to Arcane Magic",
			ko = "Antonidas' Introduction to Arcane Magic",
			cn = "Antonidas' Introduction to Arcane Magic",
		},
	},
	[465295] = {
		readable = "Medivh's Karazhan Schematics",
		model = 4198213,
		text = {
			en = "Medivh's Karazhan Schematics",
			es = "Medivh's Karazhan Schematics",
			de = "Medivh's Karazhan Schematics",
			fr = "Medivh's Karazhan Schematics",
			it = "Medivh's Karazhan Schematics",
			pt = "Medivh's Karazhan Schematics",
			ru = "Medivh's Karazhan Schematics",
			ko = "Medivh's Karazhan Schematics",
			cn = "Medivh's Karazhan Schematics",
		},
	},
	[465300] = {
		readable = "Thalen Songweaver's Notes",
		model = 1005457,
		text = {
			en = "Thalen Songweaver's Notes",
			es = "Thalen Songweaver's Notes",
			de = "Thalen Songweaver's Notes",
			fr = "Thalen Songweaver's Notes",
			it = "Thalen Songweaver's Notes",
			pt = "Thalen Songweaver's Notes",
			ru = "Thalen Songweaver's Notes",
			ko = "Thalen Songweaver's Notes",
			cn = "Thalen Songweaver's Notes",
		},
	},
	[475284] = {
		readable = "Earthen Prototype",
		model = 5205857,
		text = {
			en = "Earthen Prototype",
			es = "Earthen Prototype",
			de = "Earthen Prototype",
			fr = "Earthen Prototype",
			it = "Earthen Prototype",
			pt = "Earthen Prototype",
			ru = "Earthen Prototype",
			ko = "Earthen Prototype",
			cn = "Earthen Prototype",
		},
	},
	[475286] = {
		readable = "Overcharged Battery",
		model = 2736566,
		text = {
			en = "Overcharged Battery",
			es = "Overcharged Battery",
			de = "Overcharged Battery",
			fr = "Overcharged Battery",
			it = "Overcharged Battery",
			pt = "Overcharged Battery",
			ru = "Overcharged Battery",
			ko = "Overcharged Battery",
			cn = "Overcharged Battery",
		},
	},
	[487825] = {
		readable = "Ruffled Pages",
		model = 936429,
		text = {
			en = "Ruffled Pages",
			es = "Ruffled Pages",
			de = "Ruffled Pages",
			fr = "Ruffled Pages",
			it = "Ruffled Pages",
			pt = "Ruffled Pages",
			ru = "Ruffled Pages",
			ko = "Ruffled Pages",
			cn = "Ruffled Pages",
		},
	},
	[493375] = {
		readable = "Rune-Sealed Coffer",
		model = 1402270,
		text = {
			en = "Rune-Sealed Coffer",
			es = "Rune-Sealed Coffer",
			de = "Rune-Sealed Coffer",
			fr = "Rune-Sealed Coffer",
			it = "Rune-Sealed Coffer",
			pt = "Rune-Sealed Coffer",
			ru = "Rune-Sealed Coffer",
			ko = "Rune-Sealed Coffer",
			cn = "Rune-Sealed Coffer",
		},
	},
	[494923] = {
		readable = "Tattered Journal",
		model = 4337371,
		text = {
			en = "Tattered Journal",
			es = "Tattered Journal",
			de = "Tattered Journal",
			fr = "Tattered Journal",
			it = "Tattered Journal",
			pt = "Tattered Journal",
			ru = "Tattered Journal",
			ko = "Tattered Journal",
			cn = "Tattered Journal",
		},
	},
	[499127] = {
		readable = "Runemarked Coffer",
		model = 1402264,
		text = {
			en = "Runemarked Coffer",
			es = "Runemarked Coffer",
			de = "Runemarked Coffer",
			fr = "Runemarked Coffer",
			it = "Runemarked Coffer",
			pt = "Runemarked Coffer",
			ru = "Runemarked Coffer",
			ko = "Runemarked Coffer",
			cn = "Runemarked Coffer",
		},
	},
	[499443] = {
		readable = "Faded Journal Page",
		model = 3978479,
		text = {
			en = "Faded Journal Page",
			es = "Faded Journal Page",
			de = "Faded Journal Page",
			fr = "Faded Journal Page",
			it = "Faded Journal Page",
			pt = "Faded Journal Page",
			ru = "Faded Journal Page",
			ko = "Faded Journal Page",
			cn = "Faded Journal Page",
		},
	},
	[499620] = {
		readable = "Runed Storm Cache",
		model = 1402270,
		text = {
			en = "Runed Storm Cache",
			es = "Runed Storm Cache",
			de = "Runed Storm Cache",
			fr = "Runed Storm Cache",
			it = "Runed Storm Cache",
			pt = "Runed Storm Cache",
			ru = "Runed Storm Cache",
			ko = "Runed Storm Cache",
			cn = "Runed Storm Cache",
		},
	},
	[499862] = {
		readable = "Runed Storm Cache",
		model = 1402270,
		text = {
			en = "Runed Storm Cache",
			es = "Runed Storm Cache",
			de = "Runed Storm Cache",
			fr = "Runed Storm Cache",
			it = "Runed Storm Cache",
			pt = "Runed Storm Cache",
			ru = "Runed Storm Cache",
			ko = "Runed Storm Cache",
			cn = "Runed Storm Cache",
		},
	},
	[499863] = {
		readable = "Runed Storm Cache",
		model = 1402270,
		text = {
			en = "Runed Storm Cache",
			es = "Runed Storm Cache",
			de = "Runed Storm Cache",
			fr = "Runed Storm Cache",
			it = "Runed Storm Cache",
			pt = "Runed Storm Cache",
			ru = "Runed Storm Cache",
			ko = "Runed Storm Cache",
			cn = "Runed Storm Cache",
		},
	},
	[500407] = {
		readable = "Runed Storm Cache",
		model = 1402270,
		text = {
			en = "Runed Storm Cache",
			es = "Runed Storm Cache",
			de = "Runed Storm Cache",
			fr = "Runed Storm Cache",
			it = "Runed Storm Cache",
			pt = "Runed Storm Cache",
			ru = "Runed Storm Cache",
			ko = "Runed Storm Cache",
			cn = "Runed Storm Cache",
		},
	},
	[500688] = {
		readable = "Seafarer's Cache",
		model = 2123117,
		text = {
			en = "Seafarer's Cache",
			es = "Seafarer's Cache",
			de = "Seafarer's Cache",
			fr = "Seafarer's Cache",
			it = "Seafarer's Cache",
			pt = "Seafarer's Cache",
			ru = "Seafarer's Cache",
			ko = "Seafarer's Cache",
			cn = "Seafarer's Cache",
		},
	},
	[500689] = {
		readable = "Seafarer's Cache",
		model = 219372,
		text = {
			en = "Seafarer's Cache",
			es = "Seafarer's Cache",
			de = "Seafarer's Cache",
			fr = "Seafarer's Cache",
			it = "Seafarer's Cache",
			pt = "Seafarer's Cache",
			ru = "Seafarer's Cache",
			ko = "Seafarer's Cache",
			cn = "Seafarer's Cache",
		},
	},
	[500690] = {
		readable = "Seafarer's Cache",
		model = 446671,
		text = {
			en = "Seafarer's Cache",
			es = "Seafarer's Cache",
			de = "Seafarer's Cache",
			fr = "Seafarer's Cache",
			it = "Seafarer's Cache",
			pt = "Seafarer's Cache",
			ru = "Seafarer's Cache",
			ko = "Seafarer's Cache",
			cn = "Seafarer's Cache",
		},
	},
	[505503] = {
		readable = "Ashvane Issued Workboots",
		model = 3718225,
		text = {
			en = "Ashvane Issued Workboots",
			es = "Ashvane Issued Workboots",
			de = "Ashvane Issued Workboots",
			fr = "Ashvane Issued Workboots",
			it = "Ashvane Issued Workboots",
			pt = "Ashvane Issued Workboots",
			ru = "Ashvane Issued Workboots",
			ko = "Ashvane Issued Workboots",
			cn = "Ashvane Issued Workboots",
		},
	},
})
do ObjectDB[objectID] = objectData; end