local ObjectDB = ObjectDB; for objectID,objectData in pairs({
	[416968] = {
		readable = "Stillstone Catch",
		model = 984207,
		text = {
			en = "Stillstone Catch",
			es = "Pesca de Piedraserena",
			de = "Stillsteinfang",
			fr = "Prise de Roche-Tranquille",
			it = "Pesca di Pietraferma",
			pt = "Pesca da Águas Paradas",
			ru = "Улов из пруда Тихих камней",
			ko = "침묵바위 포획물",
			cn = "静石渔获",
		},
	},
	[416970] = {
		readable = "Hallowfall Farm Supplies",
		model = 5048188,
		text = {
			en = "Hallowfall Farm Supplies",
			es = "Suministros de granja de Santificación",
			de = "Landwirtschaftliche Vorräte von Heilsturz",
			fr = "Provisions de la ferme de Sainte-Chute",
			it = "Forniture della Fattoria dei Precipizi Sacri",
			pt = "Suprimentos da Fazenda de Pouso Santo",
			ru = "Фермерские припасы Тайносводья",
			ko = "신성한 협곡 농장 보급품",
			cn = "陨圣峪农场物资",
		},
	},
	[416971] = {
		readable = "Fallow Corn",
		model = 1709047,
		text = {
			en = "Fallow Corn",
			es = "Maíz de color pajizo",
			de = "Gelbbrauner Mais",
			fr = "Maïs de Sainte-Chute",
			it = "Mais Paglierino",
			pt = "Milho de Pousio",
			ru = "Кукуруза с поля",
			ko = "휴작 옥수수",
			cn = "闲地玉米",
		},
	},
	[416973] = {
		readable = "Arathi Toolbox",
		model = 5500648,
		text = {
			en = "Arathi Toolbox",
			es = "Caja de herramientas arathi",
			de = "Arathiwerkzeugkasten",
			fr = "Boîte à outils arathie",
			it = "Cassetta degli Attrezzi degli Arathi",
			pt = "Caixa de Ferramentas Arathi",
			ru = "Аратийский ящик с инструментами",
			ko = "아라시 연장통",
			cn = "阿拉希工具箱",
		},
	},
	[416974] = {
		readable = "Rolled Arathi-Rug",
		model = 424389,
		text = {
			en = "Rolled Arathi-Rug",
			es = "Alfombra enrollada arathi",
			de = "Aufgerollter Arathiteppich",
			fr = "Tapis arathi roulé",
			it = "Tappeto degli Arathi Arrotolato",
			pt = "Tapete Arathi Enrolado",
			ru = "Свернутый аратийский ковер",
			ko = "돌돌 말린 아라시 융단",
			cn = "卷起来的阿拉希之毯",
		},
	},
})
do ObjectDB[objectID] = objectData; end