local ObjectDB = ObjectDB; for objectID,objectData in pairs({
	[454707] = {
		readable = "Bag of Stolen Goods",
		model = 1254955,
		text = {
			en = "Bag of Stolen Goods",
			es = "Bag of Stolen Goods",
			de = "Bag of Stolen Goods",
			fr = "Bag of Stolen Goods",
			it = "Bag of Stolen Goods",
			pt = "Bag of Stolen Goods",
			ru = "Bag of Stolen Goods",
			ko = "Bag of Stolen Goods",
			cn = "Bag of Stolen Goods",
		},
	},
	[456665] = {
		readable = "Ore Sample",
		model = 5306874,
		text = {
			en = "Ore Sample",
			es = "Ore Sample",
			de = "Ore Sample",
			fr = "Ore Sample",
			it = "Ore Sample",
			pt = "Ore Sample",
			ru = "Ore Sample",
			ko = "Ore Sample",
			cn = "Ore Sample",
		},
	},
	[457143] = {
		readable = "Kaja'Cola Can",
		model = 331512,
		text = {
			en = "Kaja'Cola Can",
			es = "Kaja'Cola Can",
			de = "Kaja'Cola Can",
			fr = "Kaja'Cola Can",
			it = "Kaja'Cola Can",
			pt = "Kaja'Cola Can",
			ru = "Kaja'Cola Can",
			ko = "Kaja'Cola Can",
			cn = "Kaja'Cola Can",
		},
	},
	[464233] = {
		readable = "Bilge Rat Supply Chest",
		model = 1806321,
		text = {
			en = "Bilge Rat Supply Chest",
			es = "Bilge Rat Supply Chest",
			de = "Bilge Rat Supply Chest",
			fr = "Bilge Rat Supply Chest",
			it = "Bilge Rat Supply Chest",
			pt = "Bilge Rat Supply Chest",
			ru = "Bilge Rat Supply Chest",
			ko = "Bilge Rat Supply Chest",
			cn = "Bilge Rat Supply Chest",
		},
	},
	[465294] = {
		readable = "Antonidas' Introduction to Arcane Magic",
		model = 985165,
		text = {
			en = "Antonidas' Introduction to Arcane Magic",
			es = "Antonidas' Introduction to Arcane Magic",
			de = "Antonidas' Introduction to Arcane Magic",
			fr = "Antonidas' Introduction to Arcane Magic",
			it = "Antonidas' Introduction to Arcane Magic",
			pt = "Antonidas' Introduction to Arcane Magic",
			ru = "Antonidas' Introduction to Arcane Magic",
			ko = "Antonidas' Introduction to Arcane Magic",
			cn = "Antonidas' Introduction to Arcane Magic",
		},
	},
	[465295] = {
		readable = "Medivh's Karazhan Schematics",
		model = 4198213,
		text = {
			en = "Medivh's Karazhan Schematics",
			es = "Medivh's Karazhan Schematics",
			de = "Medivh's Karazhan Schematics",
			fr = "Medivh's Karazhan Schematics",
			it = "Medivh's Karazhan Schematics",
			pt = "Medivh's Karazhan Schematics",
			ru = "Medivh's Karazhan Schematics",
			ko = "Medivh's Karazhan Schematics",
			cn = "Medivh's Karazhan Schematics",
		},
	},
	[465300] = {
		readable = "Thalen Songweaver's Notes",
		model = 1005457,
		text = {
			en = "Thalen Songweaver's Notes",
			es = "Thalen Songweaver's Notes",
			de = "Thalen Songweaver's Notes",
			fr = "Thalen Songweaver's Notes",
			it = "Thalen Songweaver's Notes",
			pt = "Thalen Songweaver's Notes",
			ru = "Thalen Songweaver's Notes",
			ko = "Thalen Songweaver's Notes",
			cn = "Thalen Songweaver's Notes",
		},
	},
})
do ObjectDB[objectID] = objectData; end