local ObjectDB = ObjectDB; for objectID,objectData in pairs({
	[455310] = {
		readable = "Hear Historic Tales at the Storyteller Stage!",
		model = 936419,
		text = {
			en = "Hear Historic Tales at the Storyteller Stage!",
			es = "[Hear Historic Tales at the Storyteller Stage!]",
			de = "[Hear Historic Tales at the Storyteller Stage!]",
			fr = "[Hear Historic Tales at the Storyteller Stage!]",
			it = "[Hear Historic Tales at the Storyteller Stage!]",
			pt = "[Hear Historic Tales at the Storyteller Stage!]",
			ru = "[Hear Historic Tales at the Storyteller Stage!]",
			ko = "[Hear Historic Tales at the Storyteller Stage!]",
			cn = "[Hear Historic Tales at the Storyteller Stage!]",
		},
	},
	[455768] = {
		readable = "Soggy Celebration Crate",
		model = 5282318,
		text = {
			en = "Soggy Celebration Crate",
			es = "[Soggy Celebration Crate]",
			de = "[Soggy Celebration Crate]",
			fr = "[Soggy Celebration Crate]",
			it = "[Soggy Celebration Crate]",
			pt = "[Soggy Celebration Crate]",
			ru = "[Soggy Celebration Crate]",
			ko = "[Soggy Celebration Crate]",
			cn = "[Soggy Celebration Crate]",
		},
	},
	[455780] = {
		readable = "Damp Ransom Note",
		model = 943682,
		text = {
			en = "Damp Ransom Note",
			es = "[Damp Ransom Note]",
			de = "[Damp Ransom Note]",
			fr = "[Damp Ransom Note]",
			it = "[Damp Ransom Note]",
			pt = "[Damp Ransom Note]",
			ru = "[Damp Ransom Note]",
			ko = "[Damp Ransom Note]",
			cn = "[Damp Ransom Note]",
		},
	},
	[456767] = {
		readable = "Red Hair",
		model = 970251,
		text = {
			en = "Red Hair",
			es = "[Red Hair]",
			de = "[Red Hair]",
			fr = "[Red Hair]",
			it = "[Red Hair]",
			pt = "[Red Hair]",
			ru = "[Red Hair]",
			ko = "[Red Hair]",
			cn = "[Red Hair]",
		},
	},
	[456820] = {
		readable = "Strange Torch",
		model = 167130,
		text = {
			en = "Strange Torch",
			es = "[Strange Torch]",
			de = "[Strange Torch]",
			fr = "[Strange Torch]",
			it = "[Strange Torch]",
			pt = "[Strange Torch]",
			ru = "[Strange Torch]",
			ko = "[Strange Torch]",
			cn = "[Strange Torch]",
		},
	},
	[459333] = {
		readable = "Jeweled Eye",
		model = 244062,
		text = {
			en = "Jeweled Eye",
			es = "[Jeweled Eye]",
			de = "[Jeweled Eye]",
			fr = "[Jeweled Eye]",
			it = "[Jeweled Eye]",
			pt = "[Jeweled Eye]",
			ru = "[Jeweled Eye]",
			ko = "[Jeweled Eye]",
			cn = "[Jeweled Eye]",
		},
	},
	[459368] = {
		readable = "Half-Buried Chest",
		model = 4323481,
		text = {
			en = "Half-Buried Chest",
			es = "[Half-Buried Chest]",
			de = "[Half-Buried Chest]",
			fr = "[Half-Buried Chest]",
			it = "[Half-Buried Chest]",
			pt = "[Half-Buried Chest]",
			ru = "[Half-Buried Chest]",
			ko = "[Half-Buried Chest]",
			cn = "[Half-Buried Chest]",
		},
	},
})
do ObjectDB[objectID] = objectData; end