local ObjectDB = ObjectDB; for objectID,objectData in pairs({
	[466512] = {
		readable = "Crystallized Celebration Crate",
		model = 877007,
		text = {
			en = "Crystallized Celebration Crate",
			es = "[Crystallized Celebration Crate]",
			de = "[Crystallized Celebration Crate]",
			fr = "[Crystallized Celebration Crate]",
			it = "[Crystallized Celebration Crate]",
			pt = "[Crystallized Celebration Crate]",
			ru = "[Crystallized Celebration Crate]",
			ko = "[Crystallized Celebration Crate]",
			cn = "[Crystallized Celebration Crate]",
		},
	},
	[469985] = {
		readable = "Ice Block",
		model = 201047,
		text = {
			en = "Ice Block",
			es = "[Ice Block]",
			de = "[Ice Block]",
			fr = "[Ice Block]",
			it = "[Ice Block]",
			pt = "[Ice Block]",
			ru = "[Ice Block]",
			ko = "[Ice Block]",
			cn = "[Ice Block]",
		},
	},
	[473934] = {
		readable = "Property of Cooktholomew",
		model = 200884,
		text = {
			en = "Property of Cooktholomew",
			es = "[Property of Cooktholomew]",
			de = "[Property of Cooktholomew]",
			fr = "[Property of Cooktholomew]",
			it = "[Property of Cooktholomew]",
			pt = "[Property of Cooktholomew]",
			ru = "[Property of Cooktholomew]",
			ko = "[Property of Cooktholomew]",
			cn = "[Property of Cooktholomew]",
		},
	},
	[478090] = {
		readable = "Mildewed Celebration Crate",
		model = 5282318,
		text = {
			en = "Mildewed Celebration Crate",
			es = "[Mildewed Celebration Crate]",
			de = "[Mildewed Celebration Crate]",
			fr = "[Mildewed Celebration Crate]",
			it = "[Mildewed Celebration Crate]",
			pt = "[Mildewed Celebration Crate]",
			ru = "[Mildewed Celebration Crate]",
			ko = "[Mildewed Celebration Crate]",
			cn = "[Mildewed Celebration Crate]",
		},
	},
	[505260] = {
		readable = "Potion of Truth",
		model = 892744,
		text = {
			en = "Potion of Truth",
			es = "[Potion of Truth]",
			de = "[Potion of Truth]",
			fr = "[Potion of Truth]",
			it = "[Potion of Truth]",
			pt = "[Potion of Truth]",
			ru = "[Potion of Truth]",
			ko = "[Potion of Truth]",
			cn = "[Potion of Truth]",
		},
	},
})
do ObjectDB[objectID] = objectData; end