local ObjectDB = ObjectDB; for objectID,objectData in pairs({
	[474822] = {
		readable = "Runed Storm Cache",
		model = 1402270,
		text = {
			en = "Runed Storm Cache",
			es = "Runed Storm Cache",
			de = "Runed Storm Cache",
			fr = "Runed Storm Cache",
			it = "Runed Storm Cache",
			pt = "Runed Storm Cache",
			ru = "Runed Storm Cache",
			ko = "Runed Storm Cache",
			cn = "Runed Storm Cache",
		},
	},
	[494499] = {
		readable = "Seafarer's Cache",
		model = 2123117,
		text = {
			en = "Seafarer's Cache",
			es = "Seafarer's Cache",
			de = "Seafarer's Cache",
			fr = "Seafarer's Cache",
			it = "Seafarer's Cache",
			pt = "Seafarer's Cache",
			ru = "Seafarer's Cache",
			ko = "Seafarer's Cache",
			cn = "Seafarer's Cache",
		},
	},
	[500682] = {
		readable = "Seafarer's Cache",
		model = 219372,
		text = {
			en = "Seafarer's Cache",
			es = "Seafarer's Cache",
			de = "Seafarer's Cache",
			fr = "Seafarer's Cache",
			it = "Seafarer's Cache",
			pt = "Seafarer's Cache",
			ru = "Seafarer's Cache",
			ko = "Seafarer's Cache",
			cn = "Seafarer's Cache",
		},
	},
	[500683] = {
		readable = "Seafarer's Cache",
		model = 446671,
		text = {
			en = "Seafarer's Cache",
			es = "Seafarer's Cache",
			de = "Seafarer's Cache",
			fr = "Seafarer's Cache",
			it = "Seafarer's Cache",
			pt = "Seafarer's Cache",
			ru = "Seafarer's Cache",
			ko = "Seafarer's Cache",
			cn = "Seafarer's Cache",
		},
	},
	[500684] = {
		readable = "Seafarer's Cache",
		model = 446673,
		text = {
			en = "Seafarer's Cache",
			es = "Seafarer's Cache",
			de = "Seafarer's Cache",
			fr = "Seafarer's Cache",
			it = "Seafarer's Cache",
			pt = "Seafarer's Cache",
			ru = "Seafarer's Cache",
			ko = "Seafarer's Cache",
			cn = "Seafarer's Cache",
		},
	},
	[500685] = {
		readable = "Seafarer's Cache",
		model = 1706189,
		text = {
			en = "Seafarer's Cache",
			es = "Seafarer's Cache",
			de = "Seafarer's Cache",
			fr = "Seafarer's Cache",
			it = "Seafarer's Cache",
			pt = "Seafarer's Cache",
			ru = "Seafarer's Cache",
			ko = "Seafarer's Cache",
			cn = "Seafarer's Cache",
		},
	},
	[500686] = {
		readable = "Seafarer's Cache",
		model = 5771275,
		text = {
			en = "Seafarer's Cache",
			es = "Seafarer's Cache",
			de = "Seafarer's Cache",
			fr = "Seafarer's Cache",
			it = "Seafarer's Cache",
			pt = "Seafarer's Cache",
			ru = "Seafarer's Cache",
			ko = "Seafarer's Cache",
			cn = "Seafarer's Cache",
		},
	},
})
do ObjectDB[objectID] = objectData; end