local ObjectDB = ObjectDB; for objectID,objectData in pairs({
	[462417] = {
		readable = "Waterlogged Celebration Crate",
		model = 5282318,
		text = {
			en = "Waterlogged Celebration Crate",
			es = "[Waterlogged Celebration Crate]",
			de = "[Waterlogged Celebration Crate]",
			fr = "[Waterlogged Celebration Crate]",
			it = "[Waterlogged Celebration Crate]",
			pt = "[Waterlogged Celebration Crate]",
			ru = "[Waterlogged Celebration Crate]",
			ko = "[Waterlogged Celebration Crate]",
			cn = "[Waterlogged Celebration Crate]",
		},
	},
	[463539] = {
		readable = "Pilfered Earthen Chest",
		model = 5128194,
		text = {
			en = "Pilfered Earthen Chest",
			es = "Pilfered Earthen Chest",
			de = "Pilfered Earthen Chest",
			fr = "Pilfered Earthen Chest",
			it = "Pilfered Earthen Chest",
			pt = "Pilfered Earthen Chest",
			ru = "Pilfered Earthen Chest",
			ko = "Pilfered Earthen Chest",
			cn = "Pilfered Earthen Chest",
		},
	},
	[465208] = {
		readable = "Crystal Chunk",
		model = 5869303,
		text = {
			en = "Crystal Chunk",
			es = "Crystal Chunk",
			de = "Crystal Chunk",
			fr = "Crystal Chunk",
			it = "Crystal Chunk",
			pt = "Crystal Chunk",
			ru = "Crystal Chunk",
			ko = "Crystal Chunk",
			cn = "Crystal Chunk",
		},
	},
	[465272] = {
		readable = "Empty Kaja'Cola Can",
		model = 331512,
		text = {
			en = "Empty Kaja'Cola Can",
			es = "Empty Kaja'Cola Can",
			de = "Empty Kaja'Cola Can",
			fr = "Empty Kaja'Cola Can",
			it = "Empty Kaja'Cola Can",
			pt = "Empty Kaja'Cola Can",
			ru = "Empty Kaja'Cola Can",
			ko = "Empty Kaja'Cola Can",
			cn = "Empty Kaja'Cola Can",
		},
	},
	[467293] = {
		readable = "Chew Toy",
		model = 1597754,
		text = {
			en = "Chew Toy",
			es = "[Chew Toy]",
			de = "[Chew Toy]",
			fr = "[Chew Toy]",
			it = "[Chew Toy]",
			pt = "[Chew Toy]",
			ru = "[Chew Toy]",
			ko = "[Chew Toy]",
			cn = "[Chew Toy]",
		},
	},
	[467329] = {
		readable = "Maru's Toy",
		model = 4615240,
		text = {
			en = "Maru's Toy",
			es = "[Maru's Toy]",
			de = "[Maru's Toy]",
			fr = "[Maru's Toy]",
			it = "[Maru's Toy]",
			pt = "[Maru's Toy]",
			ru = "[Maru's Toy]",
			ko = "[Maru's Toy]",
			cn = "[Maru's Toy]",
		},
	},
	[475284] = {
		readable = "Earthen Prototype",
		model = 5205857,
		text = {
			en = "Earthen Prototype",
			es = "Earthen Prototype",
			de = "Earthen Prototype",
			fr = "Earthen Prototype",
			it = "Earthen Prototype",
			pt = "Earthen Prototype",
			ru = "Earthen Prototype",
			ko = "Earthen Prototype",
			cn = "Earthen Prototype",
		},
	},
	[475286] = {
		readable = "Overcharged Battery",
		model = 2736566,
		text = {
			en = "Overcharged Battery",
			es = "Overcharged Battery",
			de = "Overcharged Battery",
			fr = "Overcharged Battery",
			it = "Overcharged Battery",
			pt = "Overcharged Battery",
			ru = "Overcharged Battery",
			ko = "Overcharged Battery",
			cn = "Overcharged Battery",
		},
	},
	[499620] = {
		readable = "Runed Storm Cache",
		model = 1402270,
		text = {
			en = "Runed Storm Cache",
			es = "Runed Storm Cache",
			de = "Runed Storm Cache",
			fr = "Runed Storm Cache",
			it = "Runed Storm Cache",
			pt = "Runed Storm Cache",
			ru = "Runed Storm Cache",
			ko = "Runed Storm Cache",
			cn = "Runed Storm Cache",
		},
	},
	[499862] = {
		readable = "Runed Storm Cache",
		model = 1402270,
		text = {
			en = "Runed Storm Cache",
			es = "Runed Storm Cache",
			de = "Runed Storm Cache",
			fr = "Runed Storm Cache",
			it = "Runed Storm Cache",
			pt = "Runed Storm Cache",
			ru = "Runed Storm Cache",
			ko = "Runed Storm Cache",
			cn = "Runed Storm Cache",
		},
	},
	[499863] = {
		readable = "Runed Storm Cache",
		model = 1402270,
		text = {
			en = "Runed Storm Cache",
			es = "Runed Storm Cache",
			de = "Runed Storm Cache",
			fr = "Runed Storm Cache",
			it = "Runed Storm Cache",
			pt = "Runed Storm Cache",
			ru = "Runed Storm Cache",
			ko = "Runed Storm Cache",
			cn = "Runed Storm Cache",
		},
	},
	[500688] = {
		readable = "Seafarer's Cache",
		model = 2123117,
		text = {
			en = "Seafarer's Cache",
			es = "Seafarer's Cache",
			de = "Seafarer's Cache",
			fr = "Seafarer's Cache",
			it = "Seafarer's Cache",
			pt = "Seafarer's Cache",
			ru = "Seafarer's Cache",
			ko = "Seafarer's Cache",
			cn = "Seafarer's Cache",
		},
	},
})
do ObjectDB[objectID] = objectData; end