local ObjectDB = ObjectDB; for objectID,objectData in pairs({
	[456032] = {
		readable = "Ruffled Paper",
		model = 929401,
		text = {
			en = "Ruffled Paper",
			es = "[Ruffled Paper]",
			de = "[Ruffled Paper]",
			fr = "[Ruffled Paper]",
			it = "[Ruffled Paper]",
			pt = "[Ruffled Paper]",
			ru = "[Ruffled Paper]",
			ko = "[Ruffled Paper]",
			cn = "[Ruffled Paper]",
		},
	},
	[456036] = {
		readable = "Loose Paper",
		model = 936413,
		text = {
			en = "Loose Paper",
			es = "[Loose Paper]",
			de = "[Loose Paper]",
			fr = "[Loose Paper]",
			it = "[Loose Paper]",
			pt = "[Loose Paper]",
			ru = "[Loose Paper]",
			ko = "[Loose Paper]",
			cn = "[Loose Paper]",
		},
	},
	[456037] = {
		readable = "Scrap of Paper",
		model = 203402,
		text = {
			en = "Scrap of Paper",
			es = "[Scrap of Paper]",
			de = "[Scrap of Paper]",
			fr = "[Scrap of Paper]",
			it = "[Scrap of Paper]",
			pt = "[Scrap of Paper]",
			ru = "[Scrap of Paper]",
			ko = "[Scrap of Paper]",
			cn = "[Scrap of Paper]",
		},
	},
	[456038] = {
		readable = "Wet Paper",
		model = 305393,
		text = {
			en = "Wet Paper",
			es = "[Wet Paper]",
			de = "[Wet Paper]",
			fr = "[Wet Paper]",
			it = "[Wet Paper]",
			pt = "[Wet Paper]",
			ru = "[Wet Paper]",
			ko = "[Wet Paper]",
			cn = "[Wet Paper]",
		},
	},
	[456039] = {
		readable = "Crumpled Letter",
		model = 1331238,
		text = {
			en = "Crumpled Letter",
			es = "[Crumpled Letter]",
			de = "[Crumpled Letter]",
			fr = "[Crumpled Letter]",
			it = "[Crumpled Letter]",
			pt = "[Crumpled Letter]",
			ru = "[Crumpled Letter]",
			ko = "[Crumpled Letter]",
			cn = "[Crumpled Letter]",
		},
	},
	[456040] = {
		readable = "Scrap of Paper",
		model = 203402,
		text = {
			en = "Scrap of Paper",
			es = "[Scrap of Paper]",
			de = "[Scrap of Paper]",
			fr = "[Scrap of Paper]",
			it = "[Scrap of Paper]",
			pt = "[Scrap of Paper]",
			ru = "[Scrap of Paper]",
			ko = "[Scrap of Paper]",
			cn = "[Scrap of Paper]",
		},
	},
	[456041] = {
		readable = "Folded Paper",
		model = 311987,
		text = {
			en = "Folded Paper",
			es = "[Folded Paper]",
			de = "[Folded Paper]",
			fr = "[Folded Paper]",
			it = "[Folded Paper]",
			pt = "[Folded Paper]",
			ru = "[Folded Paper]",
			ko = "[Folded Paper]",
			cn = "[Folded Paper]",
		},
	},
	[456061] = {
		readable = "Battered Celebration Crate",
		model = 5282318,
		text = {
			en = "Battered Celebration Crate",
			es = "[Battered Celebration Crate]",
			de = "[Battered Celebration Crate]",
			fr = "[Battered Celebration Crate]",
			it = "[Battered Celebration Crate]",
			pt = "[Battered Celebration Crate]",
			ru = "[Battered Celebration Crate]",
			ko = "[Battered Celebration Crate]",
			cn = "[Battered Celebration Crate]",
		},
	},
})
do ObjectDB[objectID] = objectData; end