local ObjectDB = ObjectDB; for objectID,objectData in pairs({
	[466393] = {
		readable = "Astral Chest",
		model = 353152,
		text = {
			en = "Astral Chest",
			es = "[Astral Chest]",
			de = "[Astral Chest]",
			fr = "[Astral Chest]",
			it = "[Astral Chest]",
			pt = "[Astral Chest]",
			ru = "[Astral Chest]",
			ko = "[Astral Chest]",
			cn = "[Astral Chest]",
		},
	},
	[466400] = {
		readable = "\"Property of Elder Ko'nani\"",
		model = 4008620,
		text = {
			en = "\"Property of Elder Ko'nani\"",
			es = "[\"Property of Elder Ko'nani\"]",
			de = "[\"Property of Elder Ko'nani\"]",
			fr = "[\"Property of Elder Ko'nani\"]",
			it = "[\"Property of Elder Ko'nani\"]",
			pt = "[\"Property of Elder Ko'nani\"]",
			ru = "[\"Property of Elder Ko'nani\"]",
			ko = "[\"Property of Elder Ko'nani\"]",
			cn = "[\"Property of Elder Ko'nani\"]",
		},
	},
	[466420] = {
		readable = "Rubenstein's Safe",
		model = 203020,
		text = {
			en = "Rubenstein's Safe",
			es = "[Rubenstein's Safe]",
			de = "[Rubenstein's Safe]",
			fr = "[Rubenstein's Safe]",
			it = "[Rubenstein's Safe]",
			pt = "[Rubenstein's Safe]",
			ru = "[Rubenstein's Safe]",
			ko = "[Rubenstein's Safe]",
			cn = "[Rubenstein's Safe]",
		},
	},
	[466479] = {
		readable = "Encrypted Chest",
		model = 2907353,
		text = {
			en = "Encrypted Chest",
			es = "[Encrypted Chest]",
			de = "[Encrypted Chest]",
			fr = "[Encrypted Chest]",
			it = "[Encrypted Chest]",
			pt = "[Encrypted Chest]",
			ru = "[Encrypted Chest]",
			ko = "[Encrypted Chest]",
			cn = "[Encrypted Chest]",
		},
	},
	[466484] = {
		readable = "Encrypted Chest",
		model = 2907353,
		text = {
			en = "Encrypted Chest",
			es = "[Encrypted Chest]",
			de = "[Encrypted Chest]",
			fr = "[Encrypted Chest]",
			it = "[Encrypted Chest]",
			pt = "[Encrypted Chest]",
			ru = "[Encrypted Chest]",
			ko = "[Encrypted Chest]",
			cn = "[Encrypted Chest]",
		},
	},
	[466489] = {
		readable = "Encrypted Chest",
		model = 2907353,
		text = {
			en = "Encrypted Chest",
			es = "[Encrypted Chest]",
			de = "[Encrypted Chest]",
			fr = "[Encrypted Chest]",
			it = "[Encrypted Chest]",
			pt = "[Encrypted Chest]",
			ru = "[Encrypted Chest]",
			ko = "[Encrypted Chest]",
			cn = "[Encrypted Chest]",
		},
	},
	[466495] = {
		readable = "Encrypted Chest",
		model = 2907353,
		text = {
			en = "Encrypted Chest",
			es = "[Encrypted Chest]",
			de = "[Encrypted Chest]",
			fr = "[Encrypted Chest]",
			it = "[Encrypted Chest]",
			pt = "[Encrypted Chest]",
			ru = "[Encrypted Chest]",
			ko = "[Encrypted Chest]",
			cn = "[Encrypted Chest]",
		},
	},
	[466497] = {
		readable = "Encrypted Chest",
		model = 2907353,
		text = {
			en = "Encrypted Chest",
			es = "[Encrypted Chest]",
			de = "[Encrypted Chest]",
			fr = "[Encrypted Chest]",
			it = "[Encrypted Chest]",
			pt = "[Encrypted Chest]",
			ru = "[Encrypted Chest]",
			ko = "[Encrypted Chest]",
			cn = "[Encrypted Chest]",
		},
	},
})
do ObjectDB[objectID] = objectData; end