local ObjectDB = ObjectDB; for objectID,objectData in pairs({
	[477098] = {
		readable = "Bilge Rat Trunk",
		model = 942843,
		text = {
			en = "Bilge Rat Trunk",
			es = "Bilge Rat Trunk",
			de = "Bilge Rat Trunk",
			fr = "Bilge Rat Trunk",
			it = "Bilge Rat Trunk",
			pt = "Bilge Rat Trunk",
			ru = "Bilge Rat Trunk",
			ko = "Bilge Rat Trunk",
			cn = "Bilge Rat Trunk",
		},
	},
	[477248] = {
		readable = "Songs of the Siren",
		model = 198022,
		text = {
			en = "Songs of the Siren",
			es = "Songs of the Siren",
			de = "Songs of the Siren",
			fr = "Songs of the Siren",
			it = "Songs of the Siren",
			pt = "Songs of the Siren",
			ru = "Songs of the Siren",
			ko = "Songs of the Siren",
			cn = "Songs of the Siren",
		},
	},
	[477366] = {
		readable = "Dat-Dat's Book Stash",
		model = 2123117,
		text = {
			en = "Dat-Dat's Book Stash",
			es = "Dat-Dat's Book Stash",
			de = "Dat-Dat's Book Stash",
			fr = "Dat-Dat's Book Stash",
			it = "Dat-Dat's Book Stash",
			pt = "Dat-Dat's Book Stash",
			ru = "Dat-Dat's Book Stash",
			ko = "Dat-Dat's Book Stash",
			cn = "Dat-Dat's Book Stash",
		},
	},
	[477612] = {
		readable = "Siren Isle Manifest",
		model = 2459257,
		text = {
			en = "Siren Isle Manifest",
			es = "Siren Isle Manifest",
			de = "Siren Isle Manifest",
			fr = "Siren Isle Manifest",
			it = "Siren Isle Manifest",
			pt = "Siren Isle Manifest",
			ru = "Siren Isle Manifest",
			ko = "Siren Isle Manifest",
			cn = "Siren Isle Manifest",
		},
	},
	[505510] = {
		readable = "Barnacle-Encrusted Chest",
		text = {
			en = "Barnacle-Encrusted Chest",
			es = "Barnacle-Encrusted Chest",
			de = "Barnacle-Encrusted Chest",
			fr = "Barnacle-Encrusted Chest",
			it = "Barnacle-Encrusted Chest",
			pt = "Barnacle-Encrusted Chest",
			ru = "Barnacle-Encrusted Chest",
			ko = "Barnacle-Encrusted Chest",
			cn = "Barnacle-Encrusted Chest",
		},
	},
	[507120] = {
		readable = "Ducky Friend",
		model = 4690953,
		text = {
			en = "Ducky Friend",
			es = "Ducky Friend",
			de = "Ducky Friend",
			fr = "Ducky Friend",
			it = "Ducky Friend",
			pt = "Ducky Friend",
			ru = "Ducky Friend",
			ko = "Ducky Friend",
			cn = "Ducky Friend",
		},
	},
})
do ObjectDB[objectID] = objectData; end