local ObjectDB = ObjectDB; for objectID,objectData in pairs({
	[445275] = {
		readable = "Royal Sureki Strongbox",
		model = 5545988,
		text = {
			en = "Royal Sureki Strongbox",
			es = "Caja fuerte real sureki",
			de = "Königliche Sureki-Schließkassette",
			fr = "Coffre renforcé sureki royal",
			it = "Forziere Reale dei Sureki",
			pt = "Caixa-forte Real Sureki",
			ru = "Королевский сейф суреки",
			ko = "왕실 수레키 금고",
			cn = "皇家苏雷吉保险箱",
			tw = "Royal Sureki Strongbox",
		},
	},
	[455279] = {
		readable = "Vizier's Appreciation",
		model = 5007036,
		text = {
			en = "Vizier's Appreciation",
			es = "Agradecimiento del visir",
			de = "Anerkennung des Wesirs",
			fr = "Appréciation du vizir",
			it = "Apprezzamento del Visir",
			pt = "Gratidão do Vizir",
			ru = "Знак признательности визиря",
			ko = "재상의 감사 표시",
			cn = "宰相的感激",
			tw = "Vizier's Appreciation",
		},
	},
	[455323] = {
		readable = "Vizier's Appreciation",
		model = 5007036,
		text = {
			en = "Vizier's Appreciation",
			es = "Vizier's Appreciation",
			de = "Anerkennung des Wesirs",
			fr = "Appréciation du vizir",
			it = "Apprezzamento del Visir",
			pt = "Gratidão do Vizir",
			ru = "Знак признательности визиря",
			ko = "Vizier's Appreciation",
			cn = "宰相的感激",
			tw = "Vizier's Appreciation",
		},
	},
	[455325] = {
		readable = "Vizier's Appreciation",
		model = 5007036,
		text = {
			en = "Vizier's Appreciation",
			es = "Vizier's Appreciation",
			de = "Anerkennung des Wesirs",
			fr = "Appréciation du vizir",
			it = "Apprezzamento del Visir",
			pt = "Gratidão do Vizir",
			ru = "Знак признательности визиря",
			ko = "Vizier's Appreciation",
			cn = "Vizier's Appreciation",
			tw = "Vizier's Appreciation",
		},
	},
	[455331] = {
		readable = "Vizier's Appreciation",
		model = 5007036,
		text = {
			en = "Vizier's Appreciation",
			es = "Agradecimiento del visir",
			de = "Anerkennung des Wesirs",
			fr = "Appréciation du vizir",
			it = "Apprezzamento del Visir",
			pt = "Gratidão do Vizir",
			ru = "Знак признательности визиря",
			ko = "재상의 감사 표시",
			cn = "宰相的感激",
			tw = "Vizier's Appreciation",
		},
	},
})
do ObjectDB[objectID] = objectData; end