local ObjectDB = ObjectDB; for objectID,objectData in pairs({
	[467075] = {
		readable = "Darkmoon Fortune Card",
		model = 5334402,
		text = {
			en = "Darkmoon Fortune Card",
			es = "[Darkmoon Fortune Card]",
			de = "[Darkmoon Fortune Card]",
			fr = "[Darkmoon Fortune Card]",
			it = "[Darkmoon Fortune Card]",
			pt = "[Darkmoon Fortune Card]",
			ru = "[Darkmoon Fortune Card]",
			ko = "[Darkmoon Fortune Card]",
			cn = "[Darkmoon Fortune Card]",
		},
	},
	[467083] = {
		readable = "Darkmoon Fortune Card",
		model = 5334402,
		text = {
			en = "Darkmoon Fortune Card",
			es = "[Darkmoon Fortune Card]",
			de = "[Darkmoon Fortune Card]",
			fr = "[Darkmoon Fortune Card]",
			it = "[Darkmoon Fortune Card]",
			pt = "[Darkmoon Fortune Card]",
			ru = "[Darkmoon Fortune Card]",
			ko = "[Darkmoon Fortune Card]",
			cn = "[Darkmoon Fortune Card]",
		},
	},
	[467334] = {
		readable = "Darkmoon Fortune Card",
		model = 5334402,
		text = {
			en = "Darkmoon Fortune Card",
			es = "[Darkmoon Fortune Card]",
			de = "[Darkmoon Fortune Card]",
			fr = "[Darkmoon Fortune Card]",
			it = "[Darkmoon Fortune Card]",
			pt = "[Darkmoon Fortune Card]",
			ru = "[Darkmoon Fortune Card]",
			ko = "[Darkmoon Fortune Card]",
			cn = "[Darkmoon Fortune Card]",
		},
	},
	[467336] = {
		readable = "Darkmoon Fortune Card",
		model = 5334402,
		text = {
			en = "Darkmoon Fortune Card",
			es = "[Darkmoon Fortune Card]",
			de = "[Darkmoon Fortune Card]",
			fr = "[Darkmoon Fortune Card]",
			it = "[Darkmoon Fortune Card]",
			pt = "[Darkmoon Fortune Card]",
			ru = "[Darkmoon Fortune Card]",
			ko = "[Darkmoon Fortune Card]",
			cn = "[Darkmoon Fortune Card]",
		},
	},
	[467338] = {
		readable = "Darkmoon Fortune Card",
		model = 5334402,
		text = {
			en = "Darkmoon Fortune Card",
			es = "[Darkmoon Fortune Card]",
			de = "[Darkmoon Fortune Card]",
			fr = "[Darkmoon Fortune Card]",
			it = "[Darkmoon Fortune Card]",
			pt = "[Darkmoon Fortune Card]",
			ru = "[Darkmoon Fortune Card]",
			ko = "[Darkmoon Fortune Card]",
			cn = "[Darkmoon Fortune Card]",
		},
	},
	[467339] = {
		readable = "Darkmoon Fortune Card",
		model = 5334402,
		text = {
			en = "Darkmoon Fortune Card",
			es = "[Darkmoon Fortune Card]",
			de = "[Darkmoon Fortune Card]",
			fr = "[Darkmoon Fortune Card]",
			it = "[Darkmoon Fortune Card]",
			pt = "[Darkmoon Fortune Card]",
			ru = "[Darkmoon Fortune Card]",
			ko = "[Darkmoon Fortune Card]",
			cn = "[Darkmoon Fortune Card]",
		},
	},
	[467342] = {
		readable = "Darkmoon Fortune Card",
		model = 5334402,
		text = {
			en = "Darkmoon Fortune Card",
			es = "[Darkmoon Fortune Card]",
			de = "[Darkmoon Fortune Card]",
			fr = "[Darkmoon Fortune Card]",
			it = "[Darkmoon Fortune Card]",
			pt = "[Darkmoon Fortune Card]",
			ru = "[Darkmoon Fortune Card]",
			ko = "[Darkmoon Fortune Card]",
			cn = "[Darkmoon Fortune Card]",
		},
	},
	[467351] = {
		readable = "Darkmoon Fortune Card",
		model = 5334402,
		text = {
			en = "Darkmoon Fortune Card",
			es = "[Darkmoon Fortune Card]",
			de = "[Darkmoon Fortune Card]",
			fr = "[Darkmoon Fortune Card]",
			it = "[Darkmoon Fortune Card]",
			pt = "[Darkmoon Fortune Card]",
			ru = "[Darkmoon Fortune Card]",
			ko = "[Darkmoon Fortune Card]",
			cn = "[Darkmoon Fortune Card]",
		},
	},
	[467403] = {
		readable = "Darkmoon Fortune Card",
		model = 5334402,
		text = {
			en = "Darkmoon Fortune Card",
			es = "[Darkmoon Fortune Card]",
			de = "[Darkmoon Fortune Card]",
			fr = "[Darkmoon Fortune Card]",
			it = "[Darkmoon Fortune Card]",
			pt = "[Darkmoon Fortune Card]",
			ru = "[Darkmoon Fortune Card]",
			ko = "[Darkmoon Fortune Card]",
			cn = "[Darkmoon Fortune Card]",
		},
	},
})
do ObjectDB[objectID] = objectData; end