local ObjectDB = ObjectDB; for objectID,objectData in pairs({
	[182030] = {
		readable = "Inert Peculiar Key",
		model = 970204,
		text = {
			en = "Inert Peculiar Key",
			es = "[Inert Peculiar Key]",
			de = "[Inert Peculiar Key]",
			fr = "[Inert Peculiar Key]",
			it = "[Inert Peculiar Key]",
			pt = "[Inert Peculiar Key]",
			ru = "[Inert Peculiar Key]",
			ko = "[Inert Peculiar Key]",
			cn = "[Inert Peculiar Key]",
		},
	},
	[455310] = {
		readable = "Hear Historic Tales at the Storyteller Stage!",
		model = 936419,
		text = {
			en = "Hear Historic Tales at the Storyteller Stage!",
			es = "¡Escucha cuentos históricos en el escenario del narrador!",
			de = "Lauscht historischen Geschichten bei der Geschichtenbühne!",
			fr = "Écoutez des récits historiques à la scène du Conteur !",
			it = "Ascoltate le Storie sul Palco del Cantastorie!",
			pt = "Ouça Contos Históricos no Palco das Histórias!",
			ru = "Послушайте исторические рассказы у \"Сцены сказителя\"!",
			ko = "이야기꾼 무대에서 역사 이야기를 들어보세요!",
			cn = "快来说书人大舞台，听说书人讲述历史故事！",
		},
	},
	[455761] = {
		readable = "Gerald",
		model = 196999,
		text = {
			en = "Gerald",
			es = "Gerald",
			de = "Gerald",
			fr = "Gérald",
			it = "Gerald",
			pt = "Geraldo",
			ru = "Джеральд",
			ko = "제럴드",
			cn = "吉拉德",
		},
	},
	[455768] = {
		readable = "Soggy Celebration Crate",
		model = 5282318,
		text = {
			en = "Soggy Celebration Crate",
			es = "Cajón de celebración empapado",
			de = "Triefende Feierkiste",
			fr = "Caisse d’anniversaire trempée",
			it = "Soggy Celebration Crate",
			pt = "Caixote de Celebração Encharcado",
			ru = "Мокрый ящик с праздника",
			ko = "축축한 기념 상자",
			cn = "泡烂的庆典箱子",
		},
	},
	[456767] = {
		readable = "Red Hair",
		model = 970251,
		text = {
			en = "Red Hair",
			es = "Pelo rojo",
			de = "Rotes Haar",
			fr = "Cheveux roux",
			it = "Pelo Rosso",
			pt = "Cabelo Ruivo",
			ru = "Рыжие волосы",
			ko = "붉은색 털",
			cn = "红色毛发",
		},
	},
	[456820] = {
		readable = "Strange Torch",
		model = 167130,
		text = {
			en = "Strange Torch",
			es = "Antorcha extraña",
			de = "Merkwürdige Fackel",
			fr = "Torche étrange",
			it = "Strana Torcia",
			pt = "Tocha Estranha",
			ru = "Странный факел",
			ko = "이상한 횃불",
			cn = "奇特火把",
		},
	},
	[457025] = {
		readable = "Pre-Calibrated Goblin Transport Vessel",
		model = 315765,
		text = {
			en = "Pre-Calibrated Goblin Transport Vessel",
			es = "Transportador goblin precalibrado",
			de = "Vorkalibriertes Goblintransportschiff",
			fr = "Vaisseau de transport gobelin précalibré",
			it = "Pre-Calibrated Goblin Transport Vessel",
			pt = "Pre-Calibrated Goblin Transport Vessel",
			ru = "Откалиброванный транспортный корабль гоблинов",
			ko = "사전 보정된 고블린 수송선",
			cn = "Pre-Calibrated Goblin Transport Vessel",
		},
	},
	[457156] = {
		readable = "Torn Note",
		model = 936413,
		text = {
			en = "Torn Note",
			es = "Nota rota",
			de = "Zerrissene Notiz",
			fr = "Note déchirée",
			it = "Torn Note",
			pt = "Torn Note",
			ru = "Порванная записка",
			ko = "찢어진 쪽지",
			cn = "Torn Note",
		},
	},
	[457160] = {
		readable = "Torn Note",
		model = 936413,
		text = {
			en = "Torn Note",
			es = "Nota rota",
			de = "Zerrissene Notiz",
			fr = "Note déchirée",
			it = "Torn Note",
			pt = "Torn Note",
			ru = "Порванная записка",
			ko = "찢어진 쪽지",
			cn = "Torn Note",
		},
	},
	[457161] = {
		readable = "Torn Note",
		model = 936413,
		text = {
			en = "Torn Note",
			es = "Nota rota",
			de = "Zerrissene Notiz",
			fr = "Note déchirée",
			it = "Torn Note",
			pt = "Torn Note",
			ru = "Порванная записка",
			ko = "찢어진 쪽지",
			cn = "Torn Note",
		},
	},
	[457197] = {
		readable = "Mounted Spyglass",
		model = 4496829,
		text = {
			en = "Mounted Spyglass",
			es = "Catalejo montado",
			de = "Montiertes Fernglas",
			fr = "Longue-vue montée",
			it = "Mounted Spyglass",
			pt = "Mounted Spyglass",
			ru = "Закрепленная подзорная труба",
			ko = "거치식 망원경",
			cn = "Mounted Spyglass",
		},
	},
	[459333] = {
		readable = "Jeweled Eye",
		model = 244062,
		text = {
			en = "Jeweled Eye",
			es = "Ojo enjoyado",
			de = "Juwelenbesetztes Auge",
			fr = "Œil orné de joyaux",
			it = "Occhio Ingioiellato",
			pt = "Olho Cravejado",
			ru = "Алмазный глаз",
			ko = "보석 박힌 눈",
			cn = "宝石之眼",
		},
	},
	[459368] = {
		readable = "Half-Buried Chest",
		model = 4323481,
		text = {
			en = "Half-Buried Chest",
			es = "Cofre semienterrado",
			de = "Halb vergrabene Truhe",
			fr = "Coffre partiellement enterré",
			it = "Cassa Mezza Sepolta",
			pt = "Baú Semienterrado",
			ru = "Полузакопанный сундук",
			ko = "반쯤 묻힌 상자",
			cn = "半埋的宝箱",
		},
	},
	[463653] = {
		readable = "Dirt-Caked Celebration Crate",
		model = 5282318,
		text = {
			en = "Dirt-Caked Celebration Crate",
			es = "Cajón de celebración cubierto de tierra",
			de = "Dreckverkrustete Feierkiste",
			fr = "Caisse d’anniversaire couverte de poussière",
			it = "Dirt-Caked Celebration Crate",
			pt = "Dirt-Caked Celebration Crate",
			ru = "Грязный ящик с праздника",
			ko = "Dirt-Caked Celebration Crate",
			cn = "Dirt-Caked Celebration Crate",
		},
	},
	[465161] = {
		readable = "Water-Resistant Receipt of Sale",
		model = 936411,
		text = {
			en = "Water-Resistant Receipt of Sale",
			es = "Recibo impermeable",
			de = "Wasserfester Verkaufsbeleg",
			fr = "Récépissé de vente imperméable",
			it = "Water-Resistant Receipt of Sale",
			pt = "Water-Resistant Receipt of Sale",
			ru = "Водонепроницаемый товарный чек",
			ko = "방수 판매 영수증",
			cn = "Water-Resistant Receipt of Sale",
		},
	},
})
do ObjectDB[objectID] = objectData; end