-- A unique value which indicates the actual field within a group should not actually be Parsed (useful to bypass groups within sharedData/bubbleDown)
IGNORED_VALUE = 'E9B4EEAE-88EA-44F8-B7DF-0831B5F99A44'
POST_PROCESSING_FUNCTIONS = {};
SYMLINKS = {}

-- Special Values
DF_ACCOUNT_CAMPAIGN_QUEST = 72366;	-- Dragonflight Campaign Completed [Account]
DF_ACCOUNT_ZC_UNLOCK_QUEST = 75658;	-- Zaralek Cavern Unlocked [Account]
TWW_ACCOUNT_CAMPAIGN_QUEST = 79573;	-- The War Within Campaign Completed [Account]

-- These represent AreaID's which are able to be detected always via the in-game API checks
-- within a specific Classic version.
-- i.e. If it's only detected prior to Cataclysm, then put it in the IF BEFORE CATA preprocessor
ValidExplorationAreaIDsForClassic = {
	[604] = true,	-- Magram Village / Shok'Thokar [CATA+]
	-- #IF BEFORE CATA
	[3839] = true,	-- Abandoned Armory
	[3754] = true,	-- Altar of Sha'tar
	[4023] = true,	-- Amber Ledge
	[3723] = true,	-- Arklon Ruins
	[4001] = true,	-- Baleheim
	[4105] = true,	-- Beryl Point
	[3973] = true,	-- Blackwind Landing
	[507] = true,	-- Bluefen
	[3685] = true,	-- Bonechewer Ruins
	[4175] = true,	-- Bronze Dragonshrine
	[4484] = true,	-- Bouldercrag's Refuge
	[4055] = true,	-- Caldemere Lake
	[3879] = true,	-- Chapel Yard
	[3611] = true,	-- Clan Watch
	[18] = true,	-- Crystal Lake
	[3841] = true,	-- Darkcrest Shore
	[375] = true,	-- Deadeye Shore
	[3556] = true,	-- Den of Haal'esh
	[3939] = true,	-- Dragonmaw Fortress
	[2405] = true,	-- Ethel Rethor
	[3878] = true,	-- Ethereum Staging Grounds
	[3951] = true,	-- Evergrove
	[3541] = true,	-- Forge Camp: Mageddon
	[3548] = true,	-- Forge Camp: Rage
	[4003] = true,	-- Fort Wildervar
	[4292] = true,	-- Frenzyheart Hill
	[4066] = true,	-- Frostblade Peak
	[4022] = true,	-- Gammoth
	[3811] = true,	-- Gor'gaz Outpost
	[3798] = true,	-- Haal'eshi Gorge
	[4326] = true,	-- Heb'Drakkar
	[4523] = true,	-- Icecrown Glacier
	[3752] = true,	-- Illidari Point
	[312] = true,	-- Janeiro's Point
	[4194] = true,	-- Jintha'kalar
	[4481] = true,	-- Jintha'kalar Passage
	[2100] = true,	-- Maraudon
	[4435] = true,	-- Narvir's Cradle
	[3758] = true,	-- Netherwing Fields
	[3945] = true,	-- Netherwing Pass
	[9] = true,		-- Northshire Valley
	[4130] = true,	-- Plains of Nasam
	[3860] = true,	-- Raastok Glade
	[3887] = true,	-- Refugee Caravan
	[3893] = true,	-- Ring of Observance
	[3753] = true,	-- Ruins of Baa'ri
	[4554] = true,	-- Ruins of Shandaral
	[4250] = true,	-- Ruins of Tethys
	[3828] = true,	-- Ruuan Weald
	[3938] = true,	-- Sanctum of the Stars
	[4193] = true,	-- Scarlet Point
	[3958] = true,	-- Sha'tari Base Camp
	[3888] = true,	-- Shadow Tomb
	[3920] = true,	-- Shatter Point
	[3919] = true,	-- Singing Ridge
	[3933] = true,	-- Sketh'lon Wreckage
	[4002] = true,	-- Skorn
	[4205] = true,	-- Solstice Village
	[1940] = true,	-- Southbreak Shore
	[1578] = true,	-- Southern Savage Coast
	[3629] = true,	-- Southwind Cleft
	[3812] = true,	-- Spinebreaker Post
	[977] = true,	-- Steamwheedle Port
	[3837] = true,	-- Sunfury Hold
	[3772] = true,	-- Sylvanaar
	[3626] = true,	-- Telaar
	[3803] = true,	-- The Abyssal Shelf
	[4509] = true,	-- The Bombardment
	[3697] = true,	-- The Bone Wastes
	[4515] = true,	-- The Conflagration
	[3748] = true,	-- The Deathforge
	[4982] = true,	-- The Dranosh'ar Blockade
	[4549] = true,	-- The Great Tree
	[3729] = true,	-- The Heap
	[3771] = true,	-- The Living Grove
	[821] = true,	-- The Rolling Plains
	[301] = true,	-- The Savage Coast
	[4053] = true,	-- The Twisted Glade
	[4537] = true,	-- The Valley of Lost Hope
	[4052] = true,	-- The Vibrant Glade
	[3796] = true,	-- The Warp Fields
	[3536] = true,	-- Thrallmar
	[3769] = true,	-- Thunderlord Stronghold
	[3890] = true,	-- Tomb of Lights
	[4141] = true,	-- Torp's Farm
	[3918] = true,	-- Toshley's Station
	[3934] = true,	-- Town Square
	[3782] = true,	-- Veil Lashh
	[3689] = true,	-- Veil Reskk
	[3802] = true,	-- Void Ridge
	[3829] = true,	-- Veil Ruuan
	[3678] = true,	-- Veil Shalas
	[4200] = true,	-- Vordrassil's Heart
	[4203] = true,	-- Vordrassil's Limb
	[3821] = true,	-- Warden's Cage
	[4513] = true,	-- Ymirheim
	[3645] = true,	-- Zabra'jin
	[3763] = true,	-- Zangar Ridge
	[4323] = true,	-- Zim'Torga
	-- #ENDIF
	-- #IF AFTER CATA
	[5499] = true,	-- Akhenet Fields
	[5317] = true,	-- Bambala
	[3891] = true,	-- Carrion Hill
	[7845] = true,	-- Crystal Fissure (Highmountain)
	[3886] = true,	-- Derelict Caravan
	[7791] = true,	-- Earthmother's Bounty (Highmountain)
	[8373] = true,	-- Eye of Azshara
	[3768] = true,	-- Jagged Ridge
	[5599] = true,	-- Lost City of the Tol'vir
	[5022] = true,	-- Rim of the World (Mount Hyjal)
	[5663] = true,	-- Neferset City
	[5615] = true,	-- Pyrox Flats
	[5290] = true,	-- The Raging Chasm
	[3976] = true,	-- Veil Ala'rak
	[3889] = true,	-- Veil Rhaze
	[5666] = true,	-- Vir'naal Dam
	[3892] = true,	-- Writhing Mound
	-- #ENDIF
}